SELECT aps.AMOUNT_DUE_ORIGINAL RECEIPT_AMOUNT,
       aps.AMOUNT_DUE_REMAINING UNAPPLIED_AMOUNT,
       aps.DUE_DATE,
       DECODE (aps.STATUS,  'OP', 'OPEN',  'CL', 'CLOSED') RECEIPT_STATUS,
       aps.INVOICE_CURRENCY_CODE,
       arc.CUSTOMER_NAME,
       hps.PARTY_SITE_NUMBER,
       hcsu.SITE_USE_CODE,
       arcr.RECEIPT_NUMBER,
       arcr.RECEIPT_DATE,
       arcr.COMMENTS,
       aps.AMOUNT_APPLIED,
       aps.EXCHANGE_RATE,
       aps.EXCHANGE_DATE,
       aps.EXCHANGE_RATE_TYPE
  FROM AR_PAYMENT_SCHEDULES_ALL aps,
       AR_CUSTOMERS arc,
       HZ_CUST_SITE_USES_ALL hcsu,
       HZ_CUST_ACCT_SITES_ALL hcau,
       HZ_PARTY_SITES hps,
       AR_CASH_RECEIPTS_ALL arcr
 WHERE     aps.org_id = :P_ORG_ID
       AND aps.CUSTOMER_ID = arc.CUSTOMER_ID
       AND aps.CASH_RECEIPT_ID = arcr.CASH_RECEIPT_ID
       AND aps.CLASS = 'PMT'
       --AND aps.STATUS='OP'
       AND aps.CUSTOMER_SITE_USE_ID = hcsu.SITE_USE_ID
       AND hcsu.CUST_ACCT_SITE_ID = hcau.CUST_ACCT_SITE_ID
       AND hcau.PARTY_SITE_ID = hps.PARTY_SITE_ID
